<?php

namespace RestaurantBundle\Repository;

/**
 * DishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findValidDishes()
    {
        $qb = $this
            ->createQueryBuilder('d')
            ->where('d.status = :status')
            ->setParameter('status', 'valid')
            ->getQuery()
        ;

        return $qb->getResult();
    }
}
