<?php

namespace RestaurantBundle\Repository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findValidMenus()
    {
        $qb = $this
            ->createQueryBuilder('m')
            ->where('m.status = :status')
            ->setParameter('status', 'valid')
            ->orderBy('m.displayOrder')
            ->getQuery()
        ;

        return $qb->getResult();
    }
}
