<?php

namespace RestaurantBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * MenuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MenuRepository extends EntityRepository
{
    /**
     * @return array
     */
    public function findValidMenus()
    {
        $qb = $this
            ->createQueryBuilder('m')
            ->where('m.status = :status')
            ->setParameter('status', 'valid')
            ->orderBy('m.displayOrder')
            ->getQuery()
        ;

        return $qb->getResult();
    }

    /**
     * @return array
     */
    public function findEmptyDishesMenuList()
    {
        $qb = $this
            ->createQueryBuilder('m')
            ->leftJoin('m.dishes', 'd')
            ->where('d.id IS NULL')
            ->getQuery()
        ;

        return $qb->getResult();
    }
}
